version: '3'

services:
  app:
    build:
      context: .
    user: "${UID}:${GID}"
    restart: on-failure
    volumes:
      - ./var/etc:/app/etc:delegated
      - ./var/resources:/app/resources:delegated
    ports:
      - 9123:9123
