package handlers

const (
	moderationTestMemberStatusLeft                 = "left"
	moderationTestErrorBadGateway                  = "Bad Gateway"
	moderationTestJSONIsBot                        = "is_bot"
	moderationTestJSONFirstName                    = "first_name"
	moderationTestJSONMessageID                    = "message_id"
	moderationTestJSONDate                         = "date"
	moderationTestJSONChat                         = "chat"
	moderationTestJSONType                         = "type"
	moderationTestJSONUser                         = "user"
	moderationTestJSONStatus                       = "status"
	moderationTestJSONPermissions                  = "permissions"
	moderationTestJSONPermissionCanSendMessages    = "can_send_messages"
	moderationTestSupergroup                       = "supergroup"
	moderationTestTargetName                       = "Target"
	moderationTestFirstNameUser                    = "User"
	moderationTestFirstNameBot                     = "Test"
	moderationTestMemberStatusMember               = "member"
	moderationTestCandidateText                    = "candidate"
	moderationTestBanlistProviderPositive          = "positive"
	moderationTestTelegramMethodGetChat            = "getChat"
	moderationTestTelegramMethodGetChatMember      = "getChatMember"
	moderationTestTelegramMethodRestrictChatMember = "restrictChatMember"
)
